language: node_js
node_js:
  - "12"
  - "14"
  - "16"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
addons:
  apt:
    packages:
    - python3.7
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - musl-dev
    - libgl1-mesa-dev